### ISSUE TITLE
What toolchain are you using?

### ISSUE THREAD

**Issue by phstrauss** [jeremyong/cpp_nn_in_a_weekend#6]
To generate your blog, it looks simply gorgeous, your primary writing/formatting tool is LaTeX or something else? I would like to use the same toolchain for my blog. Thanks in advance for your answer.

**Comment by jeremyong** [comment]
Hi there! To generate my blog, I am using [Jekyll](https://jekyllrb.com/) and hosting it via github pages. To accelerate things a bit, I am using [CloudFlare](https://www.cloudflare.com/)'s free tier as a frontend cache, and also to terminate SSL with the custom domain. I author the content matter with markdown, but use the [KaTeX](https://katex.org/) as an embedded JS to render LaTeX client side (it renders math much faster and nicer than alternatives I've found). The styles themselves is just a simple CSS file I made, drawing inspiration from a lot of other blogs. Because much of it was "hand authored" as opposed to tool-generated, using the browser's built-in inspector could be used to glean how it was set up. Of course, there are various Jekyll themes you can just use to start from and adapt (which I believe is what I did some time ago). For plots, I use [Desmos](https://www.desmos.com/calculator) which can do parametric plots quite easily. I also have my own renderer and plotting tools if I need something more advanced. Finally, for various figures as you'd see in [this post](https://www.jeremyong.com/graphics/2023/01/09/tangent-spaces-and-diamond-encoding/), I use [Excalidraw](https://excalidraw.com/). Specifically, I use the VSCode Excalidraw [extension](https://marketplace.visualstudio.com/items?itemName=pomdtr.excalidraw-editor) to author the figures client-side which are easily embeddable as images in markdown.

Hopefully this helps!

**Comment by phstrauss** [comment]
Yes for sure it helps, thanks for it, one more thing, to convert from markdown to .PDF, do you use pandoc then LaTeX or something else (internal to jekyll)? My blog is there: [http://www.strauss-engineering.ch/](http://www.strauss-engineering.ch/), I also use markdown and a small static generator written in OCaml, a very interesting french descendant of standard ML. I'm in DSP and likes to see CPUs crunching numbers (well, audio samples) that's what got me deep into computing, it share a math side with graphic programming. Thanks for sharing this work on the internet, your blog will stay in my bookmarks a looong time :)
I fell in love with the Alegreya font family, take a look at this styling: [https://www.cairn.info/](https://www.cairn.info/)
All in all, I'll probably witch to jekyll in the future.

**Comment by jeremyong** [comment]
Very cool! I like signal processing quite a lot myself and occasionally do audio stuff (as you said, much of the sampling theory overlaps heavily with graphics).

For the conversion to PDF, I don't actually have an automated way to do this yet because it isn't something I've needed to do often. I have tried pandoc before, but found the workflow somewhat slow when processing very large documents. I ported the same ~100 pg document to asciidoc and also found it too slow for my liking. This is one of those things I might just implement myself someday if the need arises and if the existing tooling hasn't progressed enough. Don't get me wrong, they are amazing tools, but likely spend cycles supporting features I don't need.

**Comment by phstrauss** [comment]
Drop me an email at philippe@strauss-engineering.ch, I've got two interesting resources about sampling and interpolation functions used in DSP, I don't know about their relevance in graphics but it's still a good thing to share those ideas between different fields of engineering sometimes. It's both about non-uniform sampling.

**Comment by jeremyong** [comment]
Thanks will do! (closing this issue as resolved)
